// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-gFqFDsFXEPlJzZjLGadHPKBTx2DQjkk',
    appId: '1:1038132803886:web:6451a1b98ae8b9be3822bf',
    messagingSenderId: '1038132803886',
    projectId: 'find2sing',
    authDomain: 'find2sing.firebaseapp.com',
    storageBucket: 'find2sing.firebasestorage.app',
    measurementId: 'G-FBFQ8VGTNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgEmAx57H-zTmDygy_QaaT-7FiemWJvM',
    appId: '1:1038132803886:android:7257ebb0021a4d943822bf',
    messagingSenderId: '1038132803886',
    projectId: 'find2sing',
    storageBucket: 'find2sing.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5dZgq7fUP7Gfii2jxecGdCgbIM5pE48',
    appId: '1:1038132803886:ios:b8d977a80626b25e3822bf',
    messagingSenderId: '1038132803886',
    projectId: 'find2sing',
    storageBucket: 'find2sing.firebasestorage.app',
    iosClientId: '1038132803886-g8audousq9itpavf3huo12jtfl73e8gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarkiapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5dZgq7fUP7Gfii2jxecGdCgbIM5pE48',
    appId: '1:1038132803886:ios:33ed47119360f46f3822bf',
    messagingSenderId: '1038132803886',
    projectId: 'find2sing',
    storageBucket: 'find2sing.firebasestorage.app',
    iosClientId: '1038132803886-lei1n5omn0o41olp8s95ahj0fpscrims.apps.googleusercontent.com',
    iosBundleId: 'com.tbdigital.find2sing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-gFqFDsFXEPlJzZjLGadHPKBTx2DQjkk',
    appId: '1:1038132803886:web:feff9aeb747374043822bf',
    messagingSenderId: '1038132803886',
    projectId: 'find2sing',
    authDomain: 'find2sing.firebaseapp.com',
    storageBucket: 'find2sing.firebasestorage.app',
    measurementId: 'G-MZSZYGRWKJ',
  );

}